// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID          int64
	LogID       int64
	Coffee      string
	Method      sql.NullString
	Grind       sql.NullString
	Notes       sql.NullString
	CoffeeGrams sql.NullInt32
	WaterGrams  sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Log struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version string
}
